@startuml activity
start

:Accéder à la page d'accueil;
:Choisir un défi;
:Aller à la page du défi auquel participer;
:Lire les règles du défi;

if (Utilisateur connecté ?) then (non)
  :Se connecter ou créer un compte;
endif

repeat
  :Soumettre lien vidéo et description de la participation;
  if (Soumission valide ?) then (non)
    :Afficher message d'erreur et demander correction;
  endif
repeat while (Soumission invalide?)

:Confirmer la participation;
:Participation envoyée à la validation;
:Participation en attente de validation par un modérateur;
stop
@enduml