@startuml erd

entity User{
        *id: string
        ---
        *userName: string
        *email: string
        *password_hash: string
        avatar_url : string
        *created_at: datetime
}

entity Challenge{
        *id : string
        ---
        *title : string
        *description : string
        *rules : string
        *game : string
        *difficulty : Difficulty
        *user_id : string
        validated : boolean
        *created_at: datetime
        image_url : string?
}

entity Participation{
        *id: string
        ---
        *user_id: string
        *challenge_id: string
        *video_url: string
        description: string
        validated : boolean
        *created_at: datetime
}

entity Vote{
    *id: string
    ---
    *user_id: string
    challenge_id: string?
    participation_id: string?
    *target_type: TargetType
    *created_at: datetime
}

User ||--o{ Challenge: "creates"
User ||--o{ Participation: "submits"
User ||--o{ Vote: "votes"}
Challenge ||--o{ Participation: "has"
Challenge ||--o{ Vote: "has"
Participation ||--o{ Vote: "has"

@enduml